### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by Flou21** [Coflnet/SkyModCommands#3]
there are some security issues.

Here is a link to harbor:
https://harbor.flou.dev/harbor/projects/4/repositories/sky-mod/artifacts/sha256:6fe7fb2f18db3e05bec766cbfcf6bd02f307f3977dcf4cf28c6c42aa0fb50cef

I created a account for you, username and password are in bitwarden (coflnet organization)

the critical and the two high vulnerabilities are important

**Comment by Ekwav** [comment]
upgraded to dotnet 7
