### ISSUE TITLE
Better or more consistent "createAuction" slot identifier

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyModCommands#82]
Currently there is the `itemName` property on the data that is sent with the "createAuction" command.

Most of the time the `itemName` property is the `displayName` property of the slot in the Inventory. This is not the case for some items (I noticed it with pets):

- Command: `{"data":"{\"slot\":40,\"price\":637000.0,\"duration\":96,\"itemName\":\"[Lvl 1] Wolf\"}","level":"debug","timestamp":"2023-05-03T23:02:45.090Z","type":"createAuction"}`
- The corresponding slot: 
![grafik](https://user-images.githubusercontent.com/58751503/236069571-bcd3d8b1-723f-41a6-acdc-efc8e5254c3d.png)

The Name property inside the nbt-data also doesnt work for that, because it includes the color codes, which I would need to remove. => Also not a clean solution

The best case in by opinion would be to 

A) Respond with "Head" for pets
and
B) Also add the `uuid` to `createAuction`. If I remember correctly, there are things without a UUID, like stackable items. If there is no uuid I would just check the `displayName`. Otherwise I can just check the `uuid`.

**Comment by Ekwav** [comment]
The itemName is/was always the displayName uploaded.
I Added `Id` which is the uuid or Tag of the item if no uuid is found.
I also updated the name to be the one from hypixel nbt
